name: sphinxdocs-env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.12.7
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - alabaster==1.0.0
      - babel==2.18.0
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cssselect2==0.8.0
      - defusedxml==0.7.1
      - docutils==0.21.2
      - graphviz==0.21
      - httplib2==0.31.2
      - idna==3.11
      - imagesize==1.4.1
      - jinja2==3.1.6
      - jsonschema-rs==0.37.4
      - markupsafe==3.0.3
      - pandoc==2.4
      - pillow==12.1.1
      - plantuml==0.3.0
      - plumbum==1.10.0
      - ply==3.11
      - pycparser==3.0
      - pygments==2.19.2
      - pyparsing==3.3.2
      - requests==2.32.5
      - requests-file==2.1.0
      - roman-numerals==4.1.0
      - roman-numerals-py==4.1.0
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinx-data-viewer==0.1.5
      - sphinx-needs==6.3.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-plantuml==0.31
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sphinxcontrib-svg2pdfconverter==2.0.0
      - tinycss2==1.5.1
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - webencodings==0.5.1
